import {Inter} from 'next/font/google'
import '@/styles/reset.css'
import '@/styles/global.css'
import Header from '@/components/header/index.js'
import Footer from '@/components/footer'


const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({children}) {
    return (
        <html lang="en"
            className={
                inter.className
        }>
            <body className={
                inter.className
            }>
                <Header></Header>
                {children}
                <Footer></Footer>
            </body>
        </html>
    )
}
